export const RENDERRATE = 60;
export const TICKRATE = 10;

export const TANKSPEEDPERS = 30;
export const TANKTURNSPEEDPERS = 1;
export const BULLETSPEEDPERS = 60;

export const TANKSPEED = TANKSPEEDPERS / TICKRATE;
export const TANKTURNSPEED = TANKTURNSPEEDPERS / TICKRATE;
export const BULLETSPEED = BULLETSPEEDPERS / TICKRATE;